# Generated by Django 2.0.1 on 2018-01-25 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeDate', models.DateField(auto_now=True, verbose_name='日期')),
                ('incomeName', models.CharField(max_length=120, verbose_name='名称')),
                ('income_event_detail', models.CharField(max_length=120, null=True, verbose_name='摘要')),
                ('incomeamount', models.CharField(max_length=13, verbose_name='金额')),
            ],
            options={
                'verbose_name': '收入明细表',
                'verbose_name_plural': '收入明细表',
            },
        ),
        migrations.CreateModel(
            name='incomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(max_length=100, verbose_name='收入类型')),
            ],
            options={
                'verbose_name': '收入类型',
                'verbose_name_plural': '收入类型',
            },
        ),
        migrations.CreateModel(
            name='incomeUntype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_untype', models.CharField(max_length=100, verbose_name='支出类型')),
            ],
            options={
                'verbose_name': '支出类型',
                'verbose_name_plural': '支出类型',
            },
        ),
        migrations.CreateModel(
            name='IncomeupSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeupDate', models.DateField(auto_now=True, verbose_name='日期')),
                ('incomeupName', models.CharField(max_length=120, verbose_name='名称')),
                ('income_upevent_detail', models.CharField(max_length=120, null=True, verbose_name='摘要')),
                ('incomeupamount', models.CharField(max_length=13, verbose_name='金额')),
                ('incomeupFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb.incomeUntype')),
            ],
            options={
                'verbose_name': '支出明细表',
                'verbose_name_plural': '支出明细表',
            },
        ),
        migrations.CreateModel(
            name='salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='业务员')),
            ],
            options={
                'verbose_name': '业务员',
                'verbose_name_plural': '业务员',
            },
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('eventDetail', models.CharField(blank=True, max_length=120, null=True, verbose_name='摘要')),
                ('money', models.CharField(max_length=12, verbose_name='金额')),
                ('rate', models.CharField(max_length=12, verbose_name='利率')),
                ('interest', models.CharField(max_length=12, verbose_name='每期利息')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('daoxiri', models.DateTimeField(default=django.utils.timezone.now, verbose_name='到息日')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='联系方式')),
                ('addres', models.CharField(max_length=200, null=True, verbose_name='住址')),
                ('mortgage', models.CharField(max_length=200, null=True, verbose_name='抵押物')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='类型')),
                ('addresMortgage', models.CharField(max_length=200, null=True, verbose_name='抵押物位置')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb.salesman', verbose_name='业务员')),
            ],
            options={
                'verbose_name': '现存客户',
                'verbose_name_plural': '现存客户',
            },
        ),
        migrations.AddField(
            model_name='incomespending',
            name='incomeFor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tb.incomeType'),
        ),
    ]
