# Generated by Django 2.0.1 on 2018-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='addres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='addresMortgage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='抵押物位置'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mortgage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='抵押物'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型'),
        ),
    ]
